@startuml

note "AliceBlue" as AliceBlue #AliceBlue
note "AntiqueWhite" as AntiqueWhite #AntiqueWhite
note "Aqua" as Aqua #Aqua
note "Aquamarine" as Aquamarine #Aquamarine
note "Azure" as Azure #Azure
note "Beige" as Beige #Beige
note "Bisque" as Bisque #Bisque
note "Black" as Black #Black
note "BlanchedAlmond" as BlanchedAlmond #BlanchedAlmond
note "Blue" as Blue #Blue
note "BlueViolet" as BlueViolet #BlueViolet
note "Brown" as Brown #Brown
note "BurlyWood" as BurlyWood #BurlyWood
note "CadetBlue" as CadetBlue #CadetBlue
note "Chartreuse" as Chartreuse #Chartreuse
note "Chocolate" as Chocolate #Chocolate
note "Coral" as Coral #Coral
note "CornflowerBlue" as CornflowerBlue #CornflowerBlue
note "Cornsilk" as Cornsilk #Cornsilk
note "Crimson" as Crimson #Crimson
note "Cyan" as Cyan #Cyan
note "DarkBlue" as DarkBlue #DarkBlue
note "DarkCyan" as DarkCyan #DarkCyan
note "DarkGoldenRod" as DarkGoldenRod #DarkGoldenRod
note "DarkGray" as DarkGray #DarkGray
note "DarkGreen" as DarkGreen #DarkGreen
note "DarkGrey" as DarkGrey #DarkGrey
note "DarkKhaki" as DarkKhaki #DarkKhaki
note "DarkMagenta" as DarkMagenta #DarkMagenta
note "DarkOliveGreen" as DarkOliveGreen #DarkOliveGreen
note "DarkOrchid" as DarkOrchid #DarkOrchid
note "DarkRed" as DarkRed #DarkRed
note "DarkSalmon" as DarkSalmon #DarkSalmon
note "DarkSeaGreen" as DarkSeaGreen #DarkSeaGreen
note "DarkSlateBlue" as DarkSlateBlue #DarkSlateBlue
note "DarkSlateGray" as DarkSlateGray #DarkSlateGray
note "DarkSlateGrey" as DarkSlateGrey #DarkSlateGrey
note "DarkTurquoise" as DarkTurquoise #DarkTurquoise
note "DarkViolet" as DarkViolet #DarkViolet
note "Darkorange" as Darkorange #Darkorange
note "DeepPink" as DeepPink #DeepPink
note "DeepSkyBlue" as DeepSkyBlue #DeepSkyBlue
note "DimGray" as DimGray #DimGray
note "DimGrey" as DimGrey #DimGrey
note "DodgerBlue" as DodgerBlue #DodgerBlue
note "FireBrick" as FireBrick #FireBrick
note "FloralWhite" as FloralWhite #FloralWhite
note "ForestGreen" as ForestGreen #ForestGreen
note "Fuchsia" as Fuchsia #Fuchsia
note "Gainsboro" as Gainsboro #Gainsboro
note "GhostWhite" as GhostWhite #GhostWhite
note "Gold" as Gold #Gold
note "GoldenRod" as GoldenRod #GoldenRod
note "Gray" as Gray #Gray
note "Green" as Green #Green
note "GreenYellow" as GreenYellow #GreenYellow
note "Grey" as Grey #Grey
note "HoneyDew" as HoneyDew #HoneyDew
note "HotPink" as HotPink #HotPink
note "IndianRed" as IndianRed #IndianRed
note "Indigo" as Indigo #Indigo
note "Ivory" as Ivory #Ivory
note "Khaki" as Khaki #Khaki
note "Lavender" as Lavender #Lavender
note "LavenderBlush" as LavenderBlush #LavenderBlush
note "LawnGreen" as LawnGreen #LawnGreen
note "LemonChiffon" as LemonChiffon #LemonChiffon
note "LightBlue" as LightBlue #LightBlue
note "LightCoral" as LightCoral #LightCoral
note "LightCyan" as LightCyan #LightCyan
note "LightGoldenRodYellow" as LightGoldenRodYellow #LightGoldenRodYellow
note "LightGray" as LightGray #LightGray
note "LightGreen" as LightGreen #LightGreen
note "LightGrey" as LightGrey #LightGrey
note "LightPink" as LightPink #LightPink
note "LightSalmon" as LightSalmon #LightSalmon
note "LightSeaGreen" as LightSeaGreen #LightSeaGreen
note "LightSkyBlue" as LightSkyBlue #LightSkyBlue
note "LightSlateGray" as LightSlateGray #LightSlateGray
note "LightSlateGrey" as LightSlateGrey #LightSlateGrey
note "LightSteelBlue" as LightSteelBlue #LightSteelBlue
note "LightYellow" as LightYellow #LightYellow
note "Lime" as Lime #Lime
note "LimeGreen" as LimeGreen #LimeGreen
note "Linen" as Linen #Linen
note "Magenta" as Magenta #Magenta
note "Maroon" as Maroon #Maroon
note "MediumAquaMarine" as MediumAquaMarine #MediumAquaMarine
note "MediumBlue" as MediumBlue #MediumBlue
note "MediumOrchid" as MediumOrchid #MediumOrchid
note "MediumPurple" as MediumPurple #MediumPurple
note "MediumSeaGreen" as MediumSeaGreen #MediumSeaGreen
note "MediumSlateBlue" as MediumSlateBlue #MediumSlateBlue
note "MediumSpringGreen" as MediumSpringGreen #MediumSpringGreen
note "MediumTurquoise" as MediumTurquoise #MediumTurquoise
note "MediumVioletRed" as MediumVioletRed #MediumVioletRed
note "MidnightBlue" as MidnightBlue #MidnightBlue
note "MintCream" as MintCream #MintCream
note "MistyRose" as MistyRose #MistyRose
note "Moccasin" as Moccasin #Moccasin
note "NavajoWhite" as NavajoWhite #NavajoWhite
note "Navy" as Navy #Navy
note "OldLace" as OldLace #OldLace
note "Olive" as Olive #Olive
note "OliveDrab" as OliveDrab #OliveDrab
note "Orange" as Orange #Orange
note "OrangeRed" as OrangeRed #OrangeRed
note "Orchid" as Orchid #Orchid
note "PaleGoldenRod" as PaleGoldenRod #PaleGoldenRod
note "PaleGreen" as PaleGreen #PaleGreen
note "PaleTurquoise" as PaleTurquoise #PaleTurquoise
note "PaleVioletRed" as PaleVioletRed #PaleVioletRed
note "PapayaWhip" as PapayaWhip #PapayaWhip
note "PeachPuff" as PeachPuff #PeachPuff
note "Peru" as Peru #Peru
note "Pink" as Pink #Pink
note "Plum" as Plum #Plum
note "PowderBlue" as PowderBlue #PowderBlue
note "Purple" as Purple #Purple
note "Red" as Red #Red
note "RosyBrown" as RosyBrown #RosyBrown
note "RoyalBlue" as RoyalBlue #RoyalBlue
note "SaddleBrown" as SaddleBrown #SaddleBrown
note "Salmon" as Salmon #Salmon
note "SandyBrown" as SandyBrown #SandyBrown
note "SeaGreen" as SeaGreen #SeaGreen
note "SeaShell" as SeaShell #SeaShell
note "Sienna" as Sienna #Sienna
note "Silver" as Silver #Silver
note "SkyBlue" as SkyBlue #SkyBlue
note "SlateBlue" as SlateBlue #SlateBlue
note "SlateGray" as SlateGray #SlateGray
note "SlateGrey" as SlateGrey #SlateGrey
note "Snow" as Snow #Snow
note "SpringGreen" as SpringGreen #SpringGreen
note "SteelBlue" as SteelBlue #SteelBlue
note "Tan" as Tan #Tan
note "Teal" as Teal #Teal
note "Thistle" as Thistle #Thistle
note "Tomato" as Tomato #Tomato
note "Turquoise" as Turquoise #Turquoise
note "Violet" as Violet #Violet
note "Wheat" as Wheat #Wheat
note "White" as White #White
note "WhiteSmoke" as WhiteSmoke #WhiteSmoke
note "Yellow" as Yellow #Yellow
note "YellowGreen" as YellowGreen #YellowGreen@enduml

